# Generated by Django 5.0.8 on 2025-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_type', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=100)),
                ('flight_price', models.FloatField()),
            ],
        ),
    ]
